sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - lts/carbon
script:
  - yarn lint
  - yarn test
after_success:
  - yarn coveralls
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
